spring:
  rabbitmq:
    host: 192.168.100.110
    port: 5657
    username: admin
    password: admin
  redis:
    host: 192.168.100.110
    password: HaoKun2017
    database: 5
    port: 6379
    lettuce:
      pool:
        max-active: 80
        min-idle: 2
        max-idle: 20
        max-wait: 10000ms
      shutdown-timeout: 100ms
    jedis:
      pool:
        max-active: 80
        max-wait: 10000
        max-idle: 20
        min-idle: 2
    timeout: 30000

sharding:
  jdbc:
    datasource:
      names: master,slave0,slave1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://60.205.187.231:3306/ztjs?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        username: root
        password: hk2019
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://60.205.187.231:3306/ztjs?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        username: root
        password: hk2019
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://60.205.187.231:3306/ztjs?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        username: root
        password: hk2019
    config:
      masterslave:
        load-balance-algorithm-type: round_robin
        name: ms
        master-data-source-name: master
        slave-data-source-names: slave0,slave1
      props:
        sql:
          show: true